apiVersion: v1
kind: ServiceAccount
metadata:
  name: ecr-secret-udpater
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ecr-secret-udpater
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ecr-secret-udpater
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ecr-secret-udpater
subjects:
  - kind: ServiceAccount
    name: ecr-secret-udpater
---
apiVersion: v1
kind: Secret
metadata:
  annotations:
    description: this secret is dynamically updated by the k8s CronJob ecr-secret-update. store ECR registry user/token
  name: aws-ecr-creds
stringData:
  creds: eyJwYXlsb2FkIjoiOXFCd2pWdzdrZ3RvTzJaQytIakUwK2hWaGZHSVd0NjBnTnZ4dVppOTZjaEJFbGhiSXBvbFlNR2V0c0U3K2hjVTIyNkY1RWFTQlg4SW9OOExPRTliWjh3WVFQSHcxOVVsVjk1NngrUDhoQndTczUvOGdCaUdZSVRva3BhRUpTVUZCS0tGT3JvT0JjQ1EyZ0tDU2xWeWFWdnBkTVE4YnpQeGthUmRlRXRXMXI3OWRydTVablNnVDBBZkxRakswZm82eHpJc2xML1JSTEVXcXdBeW96Z1R6Q0pwVzZPK3dqd1Q2RUlFdS9qS1BQMDBuL1lweG1pcFhRcnVJUmUwTFR5ZkRMdFRreEM0bTRGKzZmZ1hSamRxOU5wOURFRjdvN24reXVHRUxydVZWakdOamtmWXVjanVaQzBBTVY4aXYxSGVwRW5kdzhMczk3OXVUaHJ0bWpDaXc2VjZYWmZtK1BscHQzMVUwS0N5MHIvUy9FVTFMaW1WYi94cHpSbitUYnptOEcrV0pvNk9iVzNSaS9zK3hHUU5qd3FTSE9SSzR2ZGg3V0VERWovY25CTHM3c2xKd09TY0lNTUVWQTBLUWpiU0YxSjUxTGJzazhlVzYxbXk1OTVCa3B3ZUdhaExlVlg1MXh6T1RONk1wdjNsM3VPVTFlUGRWNjc5a0VOZTVGTldpTzZoN2FVaXd6LzNORUUxZy9wQXZkalVLQ3oyK1plV05zL2JzY1B0dlRYSi9aRXVSVmtOMkp5dVNZcHpGczdvZ3ZSOWo1cmJVUlBYdnJWcEIvendQVUpSaG51OHBjdUUwZlFobWZHb3VwWDAza0s4Z0VpTG1LVlptM3d1alFNcnV3M0FZbCtaeUpMZ3F0UmltUktYZEFSYjRFbTNGYngrQ3JzYlRBcXFxNEVHTkdxQ0tFN3IybFNFT3k3Sm5yODdjWUxMMmM3V3N3cDE2Y2RvbjY1OWFrU1ErWmMzTXl1RElmdE91UUJ3S3o5SXM0Mkl1QkxGQUQrbXMwUWxsUWdMamtQanFDRzl0UktkN05WcUl0ekJac21UNXlVWE5yWktGSDJxM2hiajFlMlVFT2lwSzkwY1FFM1JYZjJJTUhOTTJSelkrOHhHZExqMGJnYVMrbml6cXRVZkhRUHNCZnRTclV5cldDNjExUk5QTkEvOEw5WXR3eS9qMGYvaXZkay9RRXZseDVRQnNMRk9sclAyb2tXWlhBc1JqUXlRTEZGb29Gc0xoeXhCQW1xNG9xdVNOWFZnOGtBTFlBczdYUXBSZW9tOFRPa0Q0a3FBTWVjZFMrakRENGdMM3lGa1d2K2JvNkM3R25DeWFmOUg4eHlTRmdraVQ4UnJYTHdoSkZFbHJJbVdRS2RXUTlwa2FKQVdodz09IiwiZGF0YWtleSI6IkFRRUJBSGh3bTBZYUlTSmVSdEptNW4xRzZ1cWVla1h1b1hYUGU1VUZjZTlScTgvMTR3QUFBSDR3ZkFZSktvWklodmNOQVFjR29HOHdiUUlCQURCb0Jna3Foa2lHOXcwQkJ3RXdIZ1lKWUlaSUFXVURCQUV1TUJFRURFMXpSblhqSFBBdU5sckQ3UUlCRUlBN25jbTEwVHg1RWNNWmxlWHc5cE56S1UrVDUva1BoUHN4dkdKODVOTnJ3dmNvWWY2UHIwVjQrMklRLzZXVUdYOVRIZ3o2ZVhRVmJpUFJWaW89IiwidmVyc2lvbiI6IjIiLCJ0eXBlIjoiREFUQV9LRVkiLCJleHBpcmF0aW9uIjoxNjk4MTY2NDM3fQ==
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: ecr-secret-update
spec:
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - args:
                - -c
                - kubectl create secret generic aws-ecr-creds --from-literal=creds=AWS:$(cat /store/token) --dry-run=client -o yaml | kubectl replace -f -
              command:
                - sh
              image: org/kubectl:v1.19.4
              name: kubectl
              volumeMounts:
                - mountPath: /store
                  name: store
          initContainers:
            - args:
                - -c
                - aws ecr get-login-password --region us-west-2 > /store/token
              command:
                - sh
              image: amazon/aws-cli:2.1.6
              name: get-login-password
              volumeMounts:
                - mountPath: /store
                  name: store
          restartPolicy: OnFailure
          serviceAccountName: ecr-secret-udpater
          volumes:
            - emptyDir:
                medium: Memory
              name: store
      ttlSecondsAfterFinished: 100
  schedule: '* */6 * * *'