apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: rollout-bluegreen
  labels:
    app: rollout-bluegreen
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: rollout-bluegreen
  template:
    metadata:
      labels:
        app: rollout-bluegreen
    spec:
      containers:
      - name: {{ .Values.name }}
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: Always
        ports:
        - containerPort: {{ .Values.servicePort }}
  strategy:
    blueGreen: 
      activeService: {{ .Values.name }}
      previewService: {{ .Values.namePreview }}
      autoPromotionEnabled: false
